# Generated by Django 2.0.5 on 2018-05-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AlterField(
            model_name='credits',
            name='credit_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
